# Generated by Django 5.2.5 on 2025-11-12 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_forumanswer_options_dmthread_dmmessage_and_more'),
        ('accounts', '0014_assessment_topic'),
    ]

    operations = [
    ]
