# Generated by Django 5.2.5 on 2026-01-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_merge_20251112_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentscore',
            old_name='enagagement',
            new_name='engagement',
        ),
        migrations.AddField(
            model_name='contentcheck',
            name='extraction_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contentcheck',
            name='extraction_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
