# Generated by Django 5.2.7 on 2026-01-29 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_chapter_policy'),
        ('accounts', '0016_user_contributor_approval_status_and_more'),
    ]

    operations = [
    ]
