# Generated by Django 5.2.5 on 2026-01-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_rename_enagagement_contentscore_engagement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentscore',
            old_name='accuracy',
            new_name='coherence',
        ),
        migrations.AddField(
            model_name='contentscore',
            name='relevance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
