# Generated by Django 5.2.5 on 2026-01-30 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_merge_20260129_1415'),
        ('accounts', '0017_rename_accuracy_contentscore_coherence_and_more'),
    ]

    operations = [
    ]
