# Generated by Django 5.2.5 on 2026-01-31 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_merge_20260130_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('resource_type', models.CharField(choices=[('youtube', 'YouTube'), ('article', 'Article'), ('docs', 'Docs/Notes'), ('other', 'Other')], default='youtube', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.chapter')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.course')),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'CONTRIBUTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='external_resources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
