# Generated by Django 5.2.5 on 2026-02-01 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_externalresource'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expertise',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='expertise',
            name='program',
        ),
    ]
