# Generated by Django 5.2.5 on 2026-02-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_expertise_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertise',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
