# Generated by Django 5.2.5 on 2026-02-02 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_expertise_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterContributionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_count', models.PositiveIntegerField(default=0)),
                ('video_count', models.PositiveIntegerField(default=0)),
                ('draft_count', models.PositiveIntegerField(default=0)),
                ('has_any_upload', models.BooleanField(default=False)),
                ('auto_submitted', models.BooleanField(default=False)),
                ('first_upload_at', models.DateTimeField(auto_now_add=True)),
                ('last_upload_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_progress', to='accounts.chapter')),
                ('contributor', models.ForeignKey(limit_choices_to={'role': 'CONTRIBUTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='chapter_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('contributor', 'chapter')},
            },
        ),
    ]
