# Generated by Django 5.2.7 on 2026-02-10 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_contentscore_accuracy_contentscore_is_best'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='ok', max_length=32)),
                ('strategy', models.CharField(default='weighted_average', max_length=64)),
                ('weights', models.JSONField(blank=True, default=dict)),
                ('thresholds', models.JSONField(blank=True, default=dict)),
                ('composite_score', models.FloatField(blank=True, null=True)),
                ('ranking', models.JSONField(blank=True, default=list)),
                ('explanation', models.TextField(blank=True, default='')),
                ('is_latest', models.BooleanField(default=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_runs', to='accounts.chapter')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_runs_decided', to=settings.AUTH_USER_MODEL)),
                ('selected_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_runs_selected', to='accounts.uploadcheck')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
