# Generated by Django 5.2.7 on 2026-02-14 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_decisionrun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentscore',
            name='relevance',
        ),
    ]
