# Generated by Django 5.2.7 on 2026-02-15 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_remove_contentscore_relevance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dmmessage',
            options={},
        ),
        migrations.AddField(
            model_name='dmmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dmmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
