# Generated by Django 5.2.7 on 2026-02-15 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_dmmessage_options_dmmessage_read_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumquestion',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forum_questions', to='accounts.chapter'),
        ),
        migrations.AddField(
            model_name='forumquestion',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forum_questions', to='accounts.course'),
        ),
    ]
