# Generated by Django 5.2.11 on 2026-02-15 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_dmmessage_options_dmmessage_read_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleasePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_percentage', models.IntegerField(default=80)),
                ('auto_release_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='release_policy', to='accounts.course')),
            ],
        ),
    ]
