# Generated by Django 5.2.7 on 2026-02-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_releasepolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumanswer',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forumanswer',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forumanswer',
            name='moderation_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='forumanswer',
            name='moderation_model',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='forumanswer',
            name='moderation_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending_review', 'Pending review'), ('rejected', 'Rejected')], default='approved', max_length=32),
        ),
        migrations.AddField(
            model_name='forumquestion',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forumquestion',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forumquestion',
            name='moderation_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='forumquestion',
            name='moderation_model',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='forumquestion',
            name='moderation_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending_review', 'Pending review'), ('rejected', 'Rejected')], default='approved', max_length=32),
        ),
    ]
