# Generated by Django 5.2.11 on 2026-02-20 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_releasepolicy'),
        ('accounts', '0029_releasepolicy'),
    ]

    operations = [
    ]
