# Generated by Django 5.2.5 on 2026-02-23 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_assessmentsource'),
        ('accounts', '0030_forumanswer_is_hidden_forumanswer_moderated_at_and_more'),
    ]

    operations = [
    ]
