# Generated by Django 5.2.11 on 2026-02-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_merge_0028_releasepolicy_0029_releasepolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasedcontent',
            name='drive_folder_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
