# Generated by Django 5.2.7 on 2026-02-22 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_forumanswer_is_hidden_forumanswer_moderated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='forum_is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='forum_suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='forum_suspension_reason',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='AssessmentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_file_id', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='ReportCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('question', 'Question'), ('answer', 'Answer / Reply'), ('user', 'User'), ('dm_message', 'Direct message')], max_length=20)),
                ('target_key', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('actioned', 'Action taken'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('needs_review', models.BooleanField(default=False)),
                ('total_reports', models.PositiveIntegerField(default=0)),
                ('distinct_reporters', models.PositiveIntegerField(default=0)),
                ('last_5_messages', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_cases', to='accounts.forumanswer')),
                ('dm_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_cases', to='accounts.dmmessage')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_cases', to='accounts.forumquestion')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('abuse_harassment', 'Abusive / Harassing'), ('hate_discrimination', 'Hate / Discrimination'), ('violence_threat', 'Violence / Threat'), ('sexual_obscene', 'Sexual / Obscene'), ('spam', 'Spam'), ('privacy', 'Privacy / Personal info'), ('cheating', 'Cheating / Academic dishonesty'), ('other', 'Other')], max_length=30)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.reportcase')),
            ],
            options={
                'unique_together': {('case', 'reporter')},
            },
        ),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('blocker', 'blocked')},
            },
        ),
    ]
