# Generated by Django 5.2.7 on 2026-02-23 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_assessmentsource'),
        ('accounts', '0031_user_forum_is_suspended_user_forum_suspended_at_and_more'),
    ]

    operations = [
    ]
