# Generated by Django 5.2.5 on 2026-02-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_merge_20260223_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasedcontent',
            name='drive_folder_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
