# Generated by Django 5.2.7 on 2026-02-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_merge_20260223_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='forum_is_suspended',
        ),
        migrations.RemoveField(
            model_name='user',
            name='forum_suspended_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='forum_suspension_reason',
        ),
        migrations.AddField(
            model_name='program',
            name='forum_is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='program',
            name='forum_suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='forum_suspension_reason',
            field=models.TextField(blank=True),
        ),
    ]
