# Generated by Django 5.2.11 on 2026-02-23 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_releasedcontent_drive_folder_id'),
        ('accounts', '0032_releasedcontent_drive_folder_id'),
    ]

    operations = [
    ]
