# Generated by Django 5.2.7 on 2026-02-24 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_releasedcontent_drive_folder_id'),
        ('accounts', '0033_remove_user_forum_is_suspended_and_more'),
    ]

    operations = [
    ]
