# Generated by Django 5.2.5 on 2026-02-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0034_merge_20260226_1123"),
    ]

    operations = [

        migrations.AddField(
            model_name="program",
            name="forum_is_suspended",
            field=models.BooleanField(default=False),
        ),

        migrations.AddField(
            model_name="program",
            name="forum_suspended_at",
            field=models.DateTimeField(null=True, blank=True),
        ),

        migrations.AddField(
            model_name="program",
            name="forum_suspension_reason",
            field=models.TextField(blank=True),
        ),
    ]
