# Generated by Django 5.2.7 on 2026-03-02 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_merge_20260224_1133'),
        ('accounts', '0035_add_program_forum_fields'),
    ]

    operations = [
    ]
