# Generated by Django 5.2.11 on 2026-03-01 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_merge_20260223_2055'),
        ('accounts', '0035_add_program_forum_fields'),
    ]

    operations = [
    ]
