# Generated by Django 5.2.11 on 2026-03-01 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_merge_20260224_1133'),
        ('accounts', '0036_merge_20260301_1307'),
    ]

    operations = [
    ]
