# Generated by Django 5.2.5 on 2026-04-05 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_merge_20260302_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=50)),
                ('low_conf_threshold', models.FloatField(default=0.5)),
                ('high_var_threshold', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='ParameterStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=50)),
                ('avg_confidence', models.FloatField(default=0)),
                ('avg_variance', models.FloatField(default=0)),
                ('usage_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='contentscore',
            name='accuracy_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentscore',
            name='accuracy_variance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentscore',
            name='clarity_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentscore',
            name='clarity_variance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentscore',
            name='coherence_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentscore',
            name='coherence_variance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentscore',
            name='completeness_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentscore',
            name='completeness_variance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentscore',
            name='engagement_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentscore',
            name='engagement_variance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentscore',
            name='final_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EvaluationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_number', models.IntegerField()),
                ('clarity', models.FloatField(blank=True, null=True)),
                ('coherence', models.FloatField(blank=True, null=True)),
                ('engagement', models.FloatField(blank=True, null=True)),
                ('completeness', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_runs', to='accounts.uploadcheck')),
            ],
            options={
                'unique_together': {('upload', 'run_number')},
            },
        ),
    ]
