# Generated by Django 5.2.7 on 2026-04-15 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_parameterconfig_parameterstats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionrun',
            name='tx_hash',
            field=models.CharField(blank=True, help_text='Blockchain transaction hash for tamper-proof audit trail', max_length=66, null=True),
        ),
    ]
