# Generated by Django 5.2.7 on 2026-04-15 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_coursecompletion_studentchapterprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('STUDENT', 'Student Completion'), ('CONTRIBUTOR', 'Contributor Release')], max_length=20)),
                ('token_id', models.PositiveIntegerField(unique=True)),
                ('tx_hash', models.CharField(max_length=100)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blockchain_certificates', to='accounts.chapter')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blockchain_certificates', to='accounts.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
