# Generated by Django 5.2.7 on 2026-04-20 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_merge_20260301_1838'),
        ('accounts', '0042_remove_program_forum_is_suspended_and_more'),
    ]

    operations = [
    ]
