# Generated by Django 5.2.7 on 2026-04-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_chaptercompletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptercompletion',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
